language: python
python:
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install codecov -U
    - pip install pytest-cov -U
    
script:
    - py.test -v --cov=pyPhenology

after_success:
    - codecov

notifications:
  email: false
