language: python
python:
    - "3.5"
    - "3.6"

install:
    #- pip install -r requirements.txt
    - pip install --only-binary=numpy,scipy numpy scipy
    - pip install -e .
    
script:
    - python test/test.py